name: Testing Git checks

on: push

jobs:
  git-checks:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Git log
      run: git log --oneline    

    - name: check commits
      run: |
        if [ -z ${{ github.event.before }} ]; then
          COMMIT_MESSAGES=$(git log --pretty=format:"%s" ${{ github.sha }})
        else
          COMMIT_MESSAGES=$(git log --pretty=format:"%s" ${{ github.event.before }}..${{ github.sha }})
        fi
      
        # Loop through each commit message and echo it
        echo "Commit Messages:"
        for commit in "${COMMIT_MESSAGES[@]}"; do
          echo "$commit"
        done