name: Testing Git checks

on: push

jobs:
  git-checks:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: check commits
      run: |
        if [ -z "060a15f89c60a85b6eec9b09f25d5309db6452ee" ]; then
          COMMIT_MESSAGES=$(git log --pretty=format:"%s" ${{ github.sha }})
        else
          COMMIT_MESSAGES=$(git log --pretty=format:"%s" ${{ github.event.before }}..${{ github.sha }})
        fi
      
        # Loop through each commit message and echo it
        echo "Commit Messages:"
        for commit in "${COMMIT_MESSAGES[@]}"; do
          echo "$commit"
        done
      