name: Testing Git checks

on: push

jobs:
  git-checks:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: check commits
      run: |
        COMMIT_MSGS = $(git log --pretty=format:"%s" ${{ github.event.after }}..${{ github.event.before }})
        for commit in $COMMIT_MSGS; do
          echo $commit
        done