name: Testing Git checks

on: push

jobs:
  git-checks:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: check commits
      run: |
        COMMIT_MESSAGES=$(git log --pretty=format:"%s" ${{ github.event.before }}..${{ github.sha }})
        PATTERN="^\[(OPS|DEVOPS|PRO)-\\d{0,9}\] [A-Za-z0-9 ]{1,50}$"
        echo "Commit Messages"
        for commit in "${COMMIT_MESSAGES[@]}"; do
          echo "$commit"
          if ! echo "$commit" | grep -qE "$PATTERN"; then
            echo "Invalid commit message format. Please folloe format: '[OPS-12345] commit message with no special characters'"
            exit 1
          fi
        done