name: Testing Git checks

on: push

jobs:
  git-checks:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: check commits
      run: |
        COMMIT_COUNT = $(echo ${{ github.event.commits.message }} | wc -l)
        echo $COMMIT_COUNT
        COMMIT_MSGS = $(git log -n $COMMIT_COUNT --pretty=format:"%s")
        for commit in $COMMIT_MSGS; do
          echo $commit
        done